[package]
name = "remconn"
version = "0.1.0"
authors = ["Anthony LAURENT <50252147+Azel-ytof@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
